### ISSUE TITLE
Extend to support jdk11 as well 

### ISSUE THREAD

**Issue by pcraig3** [LucaFeger/action-maven-cli#2]
Hi there,

I tried to use your Action on this past weekend, but you're using Maven for Java 8, whereas the app I am building is on Java 11. [There's a fork of your repo](https://github.com/xlui/action-maven-cli) that creates subfolders for Java 8 + Java 11, and [I opened up a PR against that one so that it works a bit nicer](https://github.com/xlui/action-maven-cli/pull/1).

I was wondering if you're interested in extending support in your repo to support jdk11 as well. If so, I could open up [my PR](https://github.com/xlui/action-maven-cli/pull/1) directly on your repo as you're the original Action maker (we could keep the generic action at jdk8 so it's backwards compatible).

**Comment by LucaFeger** [comment]
Hi,

the main problem I see here is that I am publishing the Action in the Workshop (it's a beta test). I wrote about it with a GitHub Staff, but it is not planned to support the multiple folder actions, like in your repository.
Actually I would say most applications are build in Java 8, so upgrading the complete Action wouldn't make sense.
I eventually will create other standalone actions for Java 10 and 11.

Please let me know if you know any workarounds for the problem.

**Comment by pcraig3** [comment]
Nope, I can't think of another way to do it if not multiple folders. That being said, I've seen a few other repos using multiple folders for different actions. 

It's not exactly the same thing, but the principle is similar. For example, [in the docker actions](https://github.com/actions/docker): [login](https://github.com/actions/docker/tree/master/login), [cli](https://github.com/actions/docker/tree/master/cli), and [tag](https://github.com/actions/docker/tree/master/cli) are all in subfolders.  (Also [Azure has a github actions repo](https://github.com/Azure/github-actions) with subfolders for different actions.) 

In any case, do whatever you think is best. I am okay using my fork at the minute, although one day I would like to delete it and use yours or someone else's Maven action.

**Comment by pcraig3** [comment]
Hey, should I close this issue, or would you like to keep it open for longer?

**Comment by LucaFeger** [comment]
I think I can close it. I will add the newer java versions as new actions, but it's a matter of time when I can add them.
