### ISSUE TITLE
Maven Install is failing

### ISSUE THREAD

**Issue by hemanth22** [LucaFeger/action-maven-cli#4]
When i have created below action it is failing with below error.

```
action "Maven Deployer" {
  uses = "LucaFeger/action-maven-cli@765e218a50f02a12a7596dc9e7321fc385888a27"
  needs = ["Maven Test"]
  runs = "install"
  secrets = ["JFrog_bintray"]
```
**Error**
```BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.

Usage: install [-cdDsp] [-o USER] [-g GRP] [-m MODE] [-t DIR] [SOURCE]... DEST

Copy files and set attributes

	-c	Just copy (default)
	-d	Create directories
	-D	Create leading target directories
	-s	Strip symbol table
	-p	Preserve date
	-o USER	Set ownership
	-g GRP	Set group ownership
	-m MODE	Set permissions
	-t DIR	Install to DIR

### FAILED Maven Deployer 16:52:15Z (31.371s)
```

and i want to know whether can i deploy my package to bintray using this github action.

FYR, please find the link of my project: https://github.com/hemanth22/GroovyLearning/tree/sonarcloudactions-jenkins3

**Comment by LucaFeger** [comment]
You are using `install` as the argument for `runs`, which overrides the ENTRYPOINT in the Dockerfile. Change `runs` to `args` and it should build your project to be sure that there are no build errors.

I don't know how bintray works, but if you can't upload it there using an official maven command, my action won't help you in this case.
